@echo off
setlocal
cd /d "%~dp0"

echo ======================================
echo   CORE-DRAW - START LATEST LOCAL
echo   URL: http://127.0.0.1:5173/
echo ======================================
echo.

echo [1/4] Stopping old server on port 5173...
for /f "tokens=5" %%a in ('netstat -aon ^| findstr ":5173" ^| findstr "LISTENING"') do (
  taskkill /PID %%a /F >nul 2>nul
)

rem package-lock.json is generated by npm and used to block auto-sync when it drifts.
rem START-LATEST owns this generated file so a stale local lock never traps the app on an old commit.
git restore -- package-lock.json >nul 2>nul

echo [2/4] Pulling latest main...
git pull --ff-only origin main
if errorlevel 1 (
  echo.
  echo Git pull failed because other local changes exist.
  echo Nothing except generated package-lock.json was overwritten.
  pause
  exit /b 1
)

echo.
echo [3/4] Syncing dependencies without rewriting package-lock...
call npm install --package-lock=false
if errorlevel 1 (
  echo.
  echo npm install failed.
  pause
  exit /b 1
)

echo.
echo [4/4] Starting fresh CORE-DRAW at http://127.0.0.1:5173/
start "" cmd /c "timeout /t 2 /nobreak >nul & start http://127.0.0.1:5173/?fresh=%RANDOM%"
call npm run dev

endlocal
